---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: sample-helm-repo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Dotisandhyarani/sample-helm-repo

